name: Actions Usage
author: Austen Stone
description: Get GitHub Actions usage for a repository
branding:
  icon: "dollar-sign"
  color: "green"

inputs:
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false
  org:
    description: The org to use for the action
    default: ${{ github.repository_owner }}
    required: false
  repo:
    description: The repository to use for the action
    default: ${{ github.repository }}
    required: false

outputs:
  ubuntu:
    description: The usage of Ubuntu in milliseconds
  macos:
    description: The usage of macOS in milliseconds
  windows:
    description: The usage of Windows in milliseconds
  total:
    description: The total usage in milliseconds
  included_minutes:
    description: The minutes included in your plan
  total_paid_minutes_used:
    description: The total paid minutes used (for prepaid)

runs:
  using: "node20"
  main: "dist/index.js"
